import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    client: "src/client.ts",
    "trpc/index": "src/api/trpc/index.ts",
    "graphql/index": "src/api/graphql/index.ts",
    "rest/index": "src/api/rest/index.ts",
    "ws/index": "src/api/ws/index.ts",
    "drizzle/index": "src/database/drizzle/index.ts",
    "mongodb/index": "src/database/mongodb/index.ts",
    "cli/index": "src/cli/index.ts",
    "templates/index": "src/templates/index.ts",
    "fields/index": "src/fields/index.ts",
    integration: "src/integration.ts",
    "api-handler": "src/api-handler.ts",
    "api-handler-graphql": "src/api-handler-graphql.ts",
    "api-handler-trpc": "src/api-handler-trpc.ts",
  },
  format: ["esm", "cjs"],
  dts: true,
  splitting: false,
  sourcemap: false,
  clean: true,
  treeshake: true,
  minify: true,
  target: "es2022",
  noExternal: [
    /^(?!(kyro:config|virtual:kyro-plugins|astro:transitions\/client|cloudflare:workers)$).*/
  ],
  platform: "node",
  external: [
    // Node built-ins (provided by Cloudflare Workers nodejs_compat)
    "crypto",
    "fs",
    "path",
    "os",
    "stream",
    "http",
    "https",
    "net",
    "tls",
    "url",
    "module",
    "buffer",
    "events",
    "util",
    "process",
    "node:sqlite",
    "node:crypto",
    "node:fs",
    "node:path",
    "node:stream",
    "node:buffer",
    // Native binary C++ Node addons (optional runtime fallbacks)
    "pg-native",
    "better-sqlite3",
    "sharp",
    // Virtual modules
    "kyro:config",
    "virtual:kyro-plugins",
    "astro:transitions/client",
    "cloudflare:workers"
  ],
});
