main = "admin/dist/server/index.mjs"
name = "kyro-app-10441c"
compatibility_date = "2026-07-31"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "admin/dist/client"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "kyro-app-10441c-d1"
database_id = "a852c0d6-2d16-4b8d-bb66-ab927b8d0ec1"

[[r2_buckets]]
binding = "STORAGE_BUCKET"
bucket_name = "kyro-media-10441c"

[alias]
"better-sqlite3" = "./cf-noop.js"
"./redis-adapter.js" = "./cf-noop.js"
"pg" = "./cf-noop.js"
"pg-native" = "./cf-noop.js"
"mongodb" = "./cf-noop.js"
"ioredis" = "./cf-noop.js"
"sharp" = "./cf-noop.js"
"ssh2" = "./cf-noop.js"
"cpu-features" = "./cf-noop.js"
"nodemailer" = "./cf-noop.js"
"node:sqlite" = "./cf-noop.js"
"basic-ftp" = "./cf-noop.js"
"node-libcurl" = "./cf-noop.js"
"net" = "./cf-noop.js"
