import { Command } from 'commander';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, resolve } from 'path';
import { glob } from 'glob';

// ============================================================================
// Type Generator
// ============================================================================

interface FieldConfig {
  name?: string;
  type: string;
  required?: boolean;
  fields?: FieldConfig[];
  relationTo?: string | string[];
  hasMany?: boolean;
  options?: Array<{ label: string; value: string }>;
}

interface CollectionConfig {
  slug: string;
  label?: string;
  fields: FieldConfig[];
}

function fieldToType(field: FieldConfig): string {
  switch (field.type) {
    case 'text':
    case 'email':
    case 'password':
    case 'textarea':
    case 'color':
    case 'code':
    case 'markdown':
    case 'date':
    case 'richtext':
    case 'json':
      return field.hasMany ? 'string[]' : 'string';
    case 'number':
      return field.hasMany ? 'number[]' : 'number';
    case 'checkbox':
      return 'boolean';
    case 'select':
    case 'radio':
      if (field.options) {
        const values = field.options.map(o => `'${o.value}'`).join(' | ');
        return field.hasMany ? `(${values})[]` : values;
      }
      return field.hasMany ? 'string[]' : 'string';
    case 'relationship':
      if (Array.isArray(field.relationTo)) {
        if (field.relationTo.includes('*')) {
          return field.hasMany ? 'any[]' : 'any';
        }
        const types = field.relationTo.map(r => `${capitalize(r)} | string`).join(' | ');
        return field.hasMany ? `(${types})[]` : `(${types})`;
      }
      const relTo = field.relationTo || 'unknown';
      if (relTo === '*') {
        return field.hasMany ? 'any[]' : 'any';
      }
      return field.hasMany ? `(${capitalize(relTo)} | string)[]` : `${capitalize(relTo)} | string`;
    case 'upload':
      return field.hasMany ? '(Media | string)[]' : 'Media | string';
    case 'array':
      if (field.fields && field.fields.length > 0) {
        const itemFields = field.fields.filter(f => f.name).map(f => {
          const type = fieldToType(f);
          return `    ${f.name}${f.required ? '' : '?'}: ${type};`;
        }).join('\n');
        return `Array<{\n${itemFields}\n  }>`;
      }
      return 'Record<string, any>[]';
    case 'group':
      if (field.fields && field.fields.length > 0) {
        const itemFields = field.fields.filter(f => f.name).map(f => {
          const type = fieldToType(f);
          return `  ${f.name}${f.required ? '' : '?'}: ${type};`;
        }).join('\n');
        return `{\n${itemFields}\n}`;
      }
      return 'Record<string, any>';
    case 'blocks':
      return 'Block[]';
    default:
      return 'any';
  }
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1).replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
}

function toCamel(str: string): string {
  return str.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
}

function collectionToInterface(collection: CollectionConfig): string {
  const name = capitalize(collection.slug);
  const fields = collection.fields.filter(f => f.name).map(f => {
    const type = fieldToType(f);
    return `  ${f.name}${f.required ? '' : '?'}: ${type};`;
  });

  // Add default fields
  fields.unshift('  id: string;');
  fields.push('  createdAt: string;');
  fields.push('  updatedAt: string;');

  return `export interface ${name} {\n${fields.join('\n')}\n}`;
}

function generateTypes(collections: CollectionConfig[]): string {
  const interfaces = collections.map(c => collectionToInterface(c));
  
  const header = `// ============================================================================
// Auto-generated by kyro generate
// ============================================================================

import type { RichTextBlock } from '@kyro-cms/core';

export interface Media {
  id: string;
  url: string;
  filename: string;
  mimeType: string;
  filesize: number;
  width?: number;
  height?: number;
  createdAt: string;
  updatedAt: string;
}

export interface Block {
  blockType: string;
  [key: string]: any;
}

`;

  const body = interfaces.join('\n\n');

  const footer = `

// ============================================================================
// Query Types
// ============================================================================

export interface KyroWhereClause {
  [field: string]: {
    equals?: any;
    not_equals?: any;
    in?: any[];
    not_in?: any[];
    greater_than?: number;
    greater_than_equal?: number;
    less_than?: number;
    less_than_equal?: number;
    like?: string;
    exists?: boolean;
  };
}

export interface KyroFindArgs {
  where?: KyroWhereClause;
  sort?: string;
  limit?: number;
  page?: number;
  depth?: number;
  select?: string[];
}

export interface KyroFindResult<T> {
  docs: T[];
  totalDocs: number;
  limit: number;
  totalPages: number;
  page: number;
  pagingCounter: number;
  hasPrevPage: boolean;
  hasNextPage: boolean;
  prevPage: number | null;
  nextPage: number | null;
}

export interface KyroCreateResult<T> {
  doc: T;
  message?: string;
}

export interface KyroUpdateResult<T> {
  doc: T;
  message?: string;
}

export interface KyroDeleteResult<T> {
  doc: T;
  message: string;
}

// ============================================================================
// Collection Map
// ============================================================================

export interface KyroCollections {
${collections.map(c => `  ${toCamel(c.slug)}: ${capitalize(c.slug)};`).join('\n')}
}

// ============================================================================
// Typed Client
// ============================================================================

export interface KyroTypedClient<C extends keyof KyroCollections> {
  find: (args?: KyroFindArgs) => Promise<KyroFindResult<KyroCollections[C]>>;
  findByID: (id: string, args?: { depth?: number; select?: string[] }) => Promise<KyroCollections[C]>;
  create: (data: Partial<KyroCollections[C]>) => Promise<KyroCreateResult<KyroCollections[C]>>;
  update: (id: string, data: Partial<KyroCollections[C]>) => Promise<KyroUpdateResult<KyroCollections[C]>>;
  delete: (id: string) => Promise<KyroDeleteResult<KyroCollections[C]>>;
  count: (args?: { where?: KyroWhereClause }) => Promise<{ totalDocs: number }>;
}

export interface KyroClient {
  ${collections.map(c => `  ${toCamel(c.slug)}: KyroTypedClient<'${c.slug}'>;`).join('\n')}
}

export function createClient(config: { url: string; token?: string }): KyroClient {
  // Client implementation would be here
  throw new Error('Not implemented');
}
`;

  return header + body + footer;
}

// ============================================================================
// CLI Command
// ============================================================================

async function fetchRemoteSchema(url: string, apiKey: string): Promise<any[]> {
  const schemaUrl = `${url.replace(/\/+$/, "")}/api/__schema`;
  const res = await fetch(schemaUrl, {
    headers: { Authorization: `ApiKey ${apiKey}` },
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Schema fetch failed (${res.status}): ${body}`);
  }
  return res.json();
}

function generateRemoteTypes(collections: any[]): string {
  let output = `// ============================================================================
// Auto-generated by kyro generate --api
// ============================================================================

import type { RichTextBlock } from '@kyro-cms/core';

export interface Media {
  id: string;
  url: string;
  filename: string;
  mimeType: string;
  filesize: number;
  width?: number;
  height?: number;
  createdAt: string;
  updatedAt: string;
}

export interface Block {
  blockType: string;
  [key: string]: any;
}

`;

  for (const col of collections) {
    const name = capitalize(col.slug);
    const fields = col.fields.filter((f: any) => f.name).map((f: any) => {
      const type = fieldToType(f);
      return `  ${f.name}${f.required ? '' : '?'}: ${type};`;
    });
    fields.unshift('  id: string;');
    fields.push('  createdAt: string;');
    fields.push('  updatedAt: string;');
    output += `export interface ${name} {\n${fields.join('\n')}\n}\n\n`;
  }

  // Typed REST Client
  output += `// ============================================================================
// Typed REST Client
// ============================================================================

export interface KyroClientOptions {
  url: string;
  apiKey: string;
  fetch?: typeof globalThis.fetch;
}

export function createKyroClient(opts: KyroClientOptions) {
  const base = opts.url.replace(/\\/+$/, "");
  const http = opts.fetch || globalThis.fetch;

  async function request<T>(path: string, init?: RequestInit): Promise<T> {
    const res = await http(\`\${base}/api\${path}\`, {
      headers: {
        "Authorization": \`ApiKey \${opts.apiKey}\`,
        "Content-Type": "application/json",
        ...init?.headers,
      },
      ...init,
    });
    if (!res.ok) {
      const body = await res.text();
      throw new Error(\`Kyro API error \${res.status}: \${body}\`);
    }
    return res.json();
  }

  function qs(params: Record<string, any>): string {
    const s = new URLSearchParams();
    for (const [k, v] of Object.entries(params)) {
      if (v !== undefined && v !== null) s.set(k, typeof v === "object" ? JSON.stringify(v) : String(v));
    }
    return s.toString();
  }

  return {
${collections.map((col: any) => {
  const name = capitalize(col.slug);
  return `    ${toCamel(col.slug)}: {
      find: (args?: { where?: Record<string, any>; sort?: string; limit?: number; page?: number; draft?: boolean }) =>
        request<{ docs: ${name}[]; totalDocs: number; page: number; totalPages: number; hasNextPage: boolean; hasPrevPage: boolean }>(\`/${col.slug}\${args ? "?" + qs(args) : ""}\`),
      findByID: (id: string, args?: { draft?: boolean }) =>
        request<${name}>(\`/${col.slug}/\${id}\${args ? "?" + qs(args) : ""}\`),
      findBySlug: (slug: string, args?: { draft?: boolean }) =>
        request<{ docs: ${name}[] }>(\`/${col.slug}?where=\${encodeURIComponent(JSON.stringify({ slug: { equals: slug } }))}\`),
      create: (data: Partial<${name}>) =>
        request<{ doc: ${name}; message?: string }>(\`/${col.slug}\`, { method: "POST", body: JSON.stringify(data) }),
      update: (id: string, data: Partial<${name}>, args?: { baseUpdatedAt?: string }) =>
        request<{ doc: ${name}; message?: string }>(\`/${col.slug}/\${id}\`, { method: "PATCH", body: JSON.stringify({ ...data, ...args }) }),
      delete: (id: string) =>
        request<{ doc: ${name}; message: string }>(\`/${col.slug}/\${id}\`, { method: "DELETE" }),
      count: (args?: { where?: Record<string, any> }) =>
        request<{ totalDocs: number }>(\`/${col.slug}/count\${args ? "?" + qs(args) : ""}\`),
    },`;
}).join('\n')}
  };
}
`;

  return output;
}

export function createGenerateCommand(): Command {
  const generate = new Command('generate')
    .description('Generate TypeScript types from collection configs')
    .option('-c, --config <path>', 'Path to config file or directory', './src/kyro')
    .option('-o, --output <path>', 'Output file path', './src/types/kyro.d.ts')
    .option('-w, --watch', 'Watch for changes and regenerate')
    .option('--url <url>', 'URL of a running Kyro CMS instance (enables remote mode)')
    .option('--api-key <key>', 'API key for authentication (required with --url)')
    .action(async (options) => {
      if (options.url) {
        if (!options.url) {
          console.error('❌ --url is required when using --api');
          process.exit(1);
        }
        if (!options.apiKey) {
          console.error('❌ --api-key is required when using --api');
          process.exit(1);
        }

        const outputPath = resolve(options.output);


        try {
          const collections = await fetchRemoteSchema(options.url, options.apiKey);


          const types = generateRemoteTypes(collections);

          const outputDir = join(outputPath, '..');
          if (!existsSync(outputDir)) {
            mkdirSync(outputDir, { recursive: true });
          }
          writeFileSync(outputPath, types);

        } catch (error: any) {
          console.error('❌ Error:', error.message);
          process.exit(1);
        }
        return;
      }

      const configPath = resolve(options.config);
      const outputPath = resolve(options.output);



      try {
        // Find all config files
        const configFiles = await glob(`${configPath}/**/*.{ts,js}`);
        
        if (configFiles.length === 0) {
          console.error('❌ No config files found at:', configPath);
          process.exit(1);
        }

        // Parse configs
        const collections: CollectionConfig[] = [];
        
        for (const file of configFiles) {
          try {
            // Dynamic import of config file
            const mod = await import(file);
            const configs = Object.values(mod).filter((v: any) => v && v.slug && v.fields);
            collections.push(...(configs as CollectionConfig[]));
          } catch (error) {
            console.warn(`⚠️  Could not parse: ${file}`);
          }
        }

        if (collections.length === 0) {
          console.error('❌ No valid collection configs found');
          process.exit(1);
        }



        // Generate types
        const types = generateTypes(collections);

        // Write output
        const outputDir = join(outputPath, '..');
        if (!existsSync(outputDir)) {
          mkdirSync(outputDir, { recursive: true });
        }

        writeFileSync(outputPath, types);


        // Watch mode
        if (options.watch) {
          const { watch } = await import('fs');
          watch(configPath, { recursive: true }, async (eventType, filename) => {

            // Regenerate
            const newCollections: CollectionConfig[] = [];
            for (const file of configFiles) {
              try {
                const mod = await import(file + `?t=${Date.now()}`);
                const configs = Object.values(mod).filter((v: any) => v && v.slug && v.fields);
                newCollections.push(...(configs as CollectionConfig[]));
              } catch {}
            }
            const newTypes = generateTypes(newCollections);
            writeFileSync(outputPath, newTypes);

          });
        }
      } catch (error: any) {
        console.error('❌ Error:', error.message);
        process.exit(1);
      }
    });

  return generate;
}

export default createGenerateCommand;
