/**
 * Helper to generate TypeScript declarations for Kyro CMS collections.
 * Can be invoked automatically during `npx astro sync` or dev server startup.
 */
export function generateKyroAstroTypes(config: Record<string, any>): string {
  const collections = config?.collections || [];
  let types = `// Auto-generated by Kyro CMS
declare module 'kyro:collections' {
  export interface KyroCollections {\n`;

  for (const col of collections) {
    const name = col.name || col.slug;
    types += `    '${name}': Record<string, any>;\n`;
  }

  types += `  }
}
`;
  return types;
}
